package bootstrap

import (
	"github.com/goravel/cos"
	"github.com/goravel/framework/ai"
	"github.com/goravel/framework/auth"
	"github.com/goravel/framework/cache"
	"github.com/goravel/framework/console"
	"github.com/goravel/framework/contracts/foundation"
	"github.com/goravel/framework/crypt"
	"github.com/goravel/framework/database"
	"github.com/goravel/framework/event"
	"github.com/goravel/framework/filesystem"
	"github.com/goravel/framework/hash"
	"github.com/goravel/framework/http"
	"github.com/goravel/framework/log"
	"github.com/goravel/framework/mail"
	"github.com/goravel/framework/process"
	"github.com/goravel/framework/queue"
	"github.com/goravel/framework/route"
	"github.com/goravel/framework/schedule"
	"github.com/goravel/framework/session"
	"github.com/goravel/framework/telemetry"
	"github.com/goravel/framework/testing"
	"github.com/goravel/framework/translation"
	"github.com/goravel/framework/validation"
	"github.com/goravel/framework/view"
	"github.com/goravel/gin"
	"github.com/goravel/minio"
	"github.com/goravel/mysql"
	"github.com/goravel/openai"
	"github.com/goravel/oss"
	"github.com/goravel/postgres"
	"github.com/goravel/redis"
	"github.com/goravel/s3"
	"github.com/wangxuancheng-dev/goravel-dm"
	"goravel/app/providers"
)

func Providers() []foundation.ServiceProvider {
	return []foundation.ServiceProvider{
		&log.ServiceProvider{},
		&console.ServiceProvider{},
		&database.ServiceProvider{},
		&redis.ServiceProvider{},
		&cache.ServiceProvider{},
		&http.ServiceProvider{},
		&route.ServiceProvider{},
		&schedule.ServiceProvider{},
		&event.ServiceProvider{},
		&queueProvider{queue.ServiceProvider{}},
		&mail.ServiceProvider{},
		&auth.ServiceProvider{},
		&hash.ServiceProvider{},
		&crypt.ServiceProvider{},
		&filesystem.ServiceProvider{},
		&validation.ServiceProvider{},
		&session.ServiceProvider{},
		&translation.ServiceProvider{},
		&testing.ServiceProvider{},
		&process.ServiceProvider{},
		&view.ServiceProvider{},
		&providers.AppServiceProvider{},
		&providers.PaymentServiceProvider{},
		&providers.SearchServiceProvider{},
		&providers.AuthServiceProvider{},
		&providers.RouteServiceProvider{},
		&providers.ConsoleServiceProvider{},
		&providers.QueueServiceProvider{},
		&providers.EventServiceProvider{},
		&providers.DatabaseServiceProvider{},
		&dm.ServiceProvider{},
		&postgres.ServiceProvider{},
		&mysql.ServiceProvider{},
		&s3.ServiceProvider{},
		&cos.ServiceProvider{},
		&oss.ServiceProvider{},
		&minio.ServiceProvider{},
		&gin.ServiceProvider{},
		&telemetry.ServiceProvider{},
		&ai.ServiceProvider{},
		&openai.ServiceProvider{},
	}
}
